### ISSUE TITLE
Invalid File records are returned from API

### ISSUE THREAD

**Issue by emsyzz** [contentful/contentful-core.php#48]
It is possible to create Asset without file name or content type with associated Upload. Even though it's not possible to process or publish such Asset due to further validations - receiving such Asset through API will result in `TypeError` and break everything.

This affects all File type resources that implement `UnprocessedFileInterface`
```
TypeError: Argument 2 passed to Contentful\Core\File\LocalUploadFile::__construct() must be of the type string, null given, called in /vendor/contentful/contentful-management/src/Mapper/Asset.php on line 64
```

**Comment by Sebb767** [comment]
Should be fully resolved now :)
