### ISSUE TITLE
Unable to debug Validation Errors because of Guzzle truncation

### ISSUE THREAD

**Issue by RayHughes** [contentful/contentful-core.php#56]
Guzzle is truncating validation errors making it extremely difficult to debug. This seems to be an issue when Guzzle is configured to throw exceptions on errors. I have traced the problem down to Requester.php and was able to output the message by printing the message body contents. https://github.com/contentful/contentful-core.php/blob/446826d86635a7538ed61a60d7541fb40fd5c277/src/Api/Requester.php#L84 

**Example of Truncated Error**

```
{
  "sys": {
    "type": "Error",
    "id": "InvalidEntry"
  },
  "message": "Validation error",
  "details": {
    "errors": {
      "err truncated ... )"
    }
  }
}
```

**Comment by Sebb767** [comment]
Hi @RayHughes ,

this is indeed annoying, but it's a problem with GuzzleHttp. You can avoid it by supplying an instance which is configured not to do so. Here's an example with the Contentful library based on [this comment](https://github.com/guzzle/guzzle/issues/2185#issuecomment-800293420):

```
// First, create the Guzzle HTTP client
$stack = new \GuzzleHttp\HandlerStack(\GuzzleHttp\Utils::chooseHandler());
$stack->push(\GuzzleHttp\Middleware::httpErrors(new \GuzzleHttp\BodySummarizer(PHP_INT_MAX)), 'http_errors');
$stack->push(\GuzzleHttp\Middleware::redirect(), 'allow_redirects');
$stack->push(\GuzzleHttp\Middleware::cookies(), 'cookies');
$stack->push(\GuzzleHttp\Middleware::prepareBody(), 'prepare_body');
$httpClient = new \GuzzleHttp\Client(['handler' => $stack ]);

// Next, create Contentful client options and set the HTTP client
$options = \Contentful\Delivery\ClientOptions::create()->withHttpClient($httpClient);

// Finally create the client with the options
$client = new \Contentful\Delivery\Client( 'b4c0n73n7fu1', 'cfexampleapi', 'master', $options);
```

Hope this helps!
