### ISSUE TITLE
getContentType() missing from SystemPropertiesInterface

### ISSUE THREAD

**Issue by Jalle19** [contentful/contentful-core.php#6]
In version 2.x of the PHP SDK, the following line of code was possible:

```php
$contentType = $resource->getContentType()->getId();
```

With version 3.x, this would be something like `$resource->getSystemProperties()->getContentType()->getId()`, however, only the actual `SystemProperties` implementation has the `getContentType()` method, not the interface.

**Comment by dborsatto** [comment]
That shortcut method is still available on the entry class on v3 🤔

**Comment by dborsatto** [comment]
The interface has only the very minimum set of methods that should always be present in all situations, and those are for retrieving ID and type. Content type is specific to entries, and that's why the base interface does not include the getContentType method ☺️

**Comment by Jalle19** [comment]
I see. I worked around it with `@var` annotations so it's fine.
